### ISSUE TITLE
update: EPA Clearance

### ISSUE THREAD

**Issue by jhollist** [USEPA/lakemorpho_manuscript#1]
@jsta just a quick update...  

The manuscript is working its way through our clearance process.  I'm hoping that it should be finished with that in 3-4 weeks.  Once that is done I will submit to F1000Research!

They will ask for reviewers.  Luckily there is no real shortage of R/Lakes people.  I was thinking of suggesting Gavin Simpson, Jordan Read, Simon Goring, Hilary Dugan, and Samantha Oliver.  You have any additional ideas for reviewers?

**Comment by jsta** [comment]
Thats a nice list! One name that comes to mind is Kait Farrell or someone else in Cayelan Carey's lab. I had conversations with her (Cayelan) about lakemorpho.

**Comment by jhollist** [comment]
Just saw your response.  Good addition. I'll add Kait or someone to the list.

Also, one more approval left and I'll be ready to submit!  Should be out the door in a few weeks.

**Comment by jhollist** [comment]
Through clearance!  Should hopefully have this submitted next week sometime (although M-W are a bit crazy...)
